# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  - conda-forge::python>=3.12
  - conda-forge::pip
  - pip:
      - click~=8.1
      - git+https://github.com/timrozday-mgnify/ena-api-client.git
      - git+https://github.com/timrozday-mgnify/linkml-lib.git
      - git+https://github.com/timrozday-mgnify/ena-submission-toolkit.git
