lint:
  container_configs: false
  files_exist:
    - conf/igenomes.config
    - conf/igenomes_ignored.config
  nextflow_config:
    - params.input
  files_unchanged:
    - .github/PULL_REQUEST_TEMPLATE.md
    - docs/images/nf-core-seqsubmit_logo_light.png
    - docs/images/nf-core-seqsubmit_logo_dark.png
    - assets/nf-core-seqsubmit_logo_light.png
nf_core_version: 4.0.2
repository_type: pipeline
template:
  author: Martin Beracochea, Ekaterina Sakharova, Sofia Ochkalova, Evangelos Karatzas, Tim Rozday
  description: Submit sequences, assemblies, MAGs, etc., to public archives
  force: false
  is_nfcore: true
  name: seqsubmit
  org: nf-core
  outdir: .
  skip_features:
    - igenomes
    - fastqc
    - gpu
  version: 1.0.0
