/*
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Nextflow config file for running minimal tests
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Defines input files and everything required to run a fast and simple pipeline test.

    Use as follows:
        nextflow run nf-core/seqsubmit -profile test,<docker/singularity> --outdir <OUTDIR>

----------------------------------------------------------------------------------------
*/

process {
    resourceLimits = [
        cpus: 2,
        memory: '16.GB',
        time: '1.h'
    ]
}

params {
    config_profile_name        = 'Test --mode mags multiple_bins_missing_metadata profile'
    config_profile_description = 'Multi-bin MAG test with mixed missing metadata fields'

    // Input data
    input            = params.pipelines_testdata_base_path + 'seqsubmit/samplesheets/mag_multiple_bins_missing_metadata.csv'

    mode             = "mags"
    submission_study = "PRJEB98843"
    centre_name      = "TEST_CENTER"

    test_upload      = true

    cat_db           = params.pipelines_testdata_base_path + 'seqsubmit/test_data/small_cat_db/tax-db.tar.gz'
    checkm2_db       = null

}
