/*
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Nextflow config file for running minimal tests
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Defines input files and everything required to run a fast and simple pipeline test.

    Use as follows:
        nextflow run nf-core/seqsubmit -profile test,<docker/singularity> --outdir <OUTDIR>

----------------------------------------------------------------------------------------
*/

process {
    resourceLimits = [
        cpus: 2,
        memory: '12.GB',
        time: '1.h'
    ]
}

params {
    config_profile_name        = 'Test --mode mags complete_metadata profile'
    config_profile_description = 'Single-case MAG test with complete metadata values provided'

    // Input data
    input            = params.pipelines_testdata_base_path + 'seqsubmit/samplesheets/mag_complete_metadata.csv'

    mode             = "mags"
    submission_study = "PRJEB98843"
    centre_name      = "TEST_CENTER"

    test_upload      = true

    cat_db           = null
    checkm2_db       = null

}
